version: '3.1'

services:
  web:
    build: ./
    depends_on:
      - db
    ports:
      - 127.0.0.1:19001:3000
  db:
    image: postgres:12.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=thisissomelongpassword
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:19080:8080
    depends_on:
      - db
